version: 2

build:
  os: ubuntu-22.04

sphinx:
  configuration: docs/source/conf.py

conda:
  environment: docs/.environment.yml

python:
  install:
    - method: pip
      path: .
  system_packages: true
