language: python

python:
    - 3.6

env:
    - NUMPY_VERSION=1.15

cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.conda
        - $HOME/.astropy/cache/halotools

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n buildenv python=$TRAVIS_PYTHON_VERSION
    - source activate buildenv
    - conda config --add channels astropy
    - conda config --add channels bccp
    - conda install --yes numpy=$NUMPY_VERSION
    - echo "numpy $NUMPY_VERSION.*" >> $CONDA_PREFIX/conda-meta/pinned
    - conda install --yes --file requirements.txt

script:
    - pytest --runslow harmonia/tests/
