name: harmonia-docs

channels:
    - conda-forge
    - bccp
    - defaults

dependencies:
    - python=3.8
    - numpy
    - scipy
    - astropy
    - healpy
    - nbodykit
    - pip
    - sphinx
    - IPython
    - numpydoc
    - nbsphinx
